apiVersion: v1
kind: Service
metadata:
  name: fibonacci-client-1-0-1
  labels:
    app: fibonacci-client-1-0-1
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: fibonacci-client-1-0-1
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Local

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci-client-1-0-1
spec:
  selector:
    matchLabels:
      app: fibonacci-client-1-0-1
  replicas: 1
  template:
    metadata:
      labels:
        app: fibonacci-client-1-0-1
    spec:
      containers:
      - name: fibonacci-client
        image: deciphernow/fibonacci:client-latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "500m"
          limits:
            cpu: "1000m"
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HOST
          value: "fibonacci-1-0-1.$(POD_NAMESPACE)"
        - name: PORT
          value: "8081"
      imagePullSecrets:
        - name: dockerhubcred
